### ISSUE TITLE
Scrolling issues on Chrome (112)?

### ISSUE THREAD

**Issue by jwyg** [PublicDataLab/offshoreatlas#11]
https://offshoreatlas.publicdatalab.org/ - seems not to want to scroll on Chrome (112 - including in incognito, with fresh profile, with no extensions). It used to work on Chrome and still works on other browsers. Adding this issue in case others also can't access / this is a browser compatibility problem...

**Comment by mikima** [comment]
the whole project seems that have some issues with the latest version of Chrome :/
